# Databricks notebook source
# MAGIC %md
# MAGIC ### Research output transform config
# MAGIC Covers all 7 Scholarly Activities subtypes (Book, Chapter, Journal,
# MAGIC Proceeding, Patent, Other, Editorial) � they share one raw JSON shape
# MAGIC in Pure, only `subtype` differs; subtype-specific column selection
# MAGIC happens in Part 3. See transform_engine.py's module docstring for the
# MAGIC action vocabulary used here.
# MAGIC
# MAGIC A plain data file, no logic � same content as the JSON config it
# MAGIC replaced, just loaded via `%run` instead of `open()` (this
# MAGIC workspace only reliably resolves Databricks-recognized notebook files,
# MAGIC not plain `.json`; see the root README).

# COMMAND ----------

RESEARCH_OUTPUT_TRANSFORM_CONFIG = {   'pureId': {'actions': [{'type': 'cast', 'to_type': 'string'}]},
    'type.term.en_GB': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'subtype'}]},
    'identifiers': {   'actions': [   {'type': 'add'},
                                      {   'type': 'extract_from_list',
                                          'match': {'path': ['idSource'], 'equals': 'Scopus'},
                                          'value_path': ['value'],
                                          'to': 'scopus_id'},
                                      {'type': 'drop'}]},
    'title.value': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'title'}]},
    'subTitle.value': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'subTitle'}]},
    'publicationStatuses': {   'actions': [   {'type': 'add'},
                                              {   'type': 'extract_from_list',
                                                  'match': {   'path': ['current'],
                                                               'equals': True,
                                                               'fallback': 'first_item'},
                                                  'value_path': [   'publicationStatus',
                                                                    'term',
                                                                    'en_GB'],
                                                  'to': 'status'},
                                              {   'type': 'extract_from_list',
                                                  'match': {   'path': ['current'],
                                                               'equals': True,
                                                               'fallback': 'first_item'},
                                                  'value_path': ['publicationDate', 'year'],
                                                  'to': 'statusYear'},
                                              {   'type': 'extract_from_list',
                                                  'match': {   'path': ['current'],
                                                               'equals': True,
                                                               'fallback': 'first_item'},
                                                  'value_path': ['publicationDate', 'month'],
                                                  'to': 'statusMonth'},
                                              {   'type': 'extract_from_list',
                                                  'match': {   'path': ['current'],
                                                               'equals': True,
                                                               'fallback': 'first_item'},
                                                  'value_path': ['publicationDate', 'day'],
                                                  'to': 'statusDay'},
                                              {'type': 'drop'}]},
    'organizations': {   'actions': [   {'type': 'add'},
                                        {   'type': 'join_from_list',
                                            'value_path': ['uuid'],
                                            'to': 'organizations'}]},
    'links': {   'actions': [   {'type': 'add'},
                                {'type': 'join_from_list', 'value_path': ['url'], 'to': 'url'},
                                {'type': 'drop'}]},
    'event.uuid': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'event_uuid'}]},
    'journalAssociation.issn.issn': {   'actions': [   {'type': 'add'},
                                                       {'type': 'rename', 'to': 'issn'}]},
    'journalAssociation.title.title': {   'actions': [   {'type': 'add'},
                                                         {   'type': 'rename',
                                                             'to': 'journal_title'}]},
    'journalAssociation.journal.uuid': {   'actions': [   {'type': 'add'},
                                                          {'type': 'rename', 'to': 'journal_id'}]},
    'abstract.en_GB': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'abstract'}]},
    'electronicVersions': {   'actions': [   {'type': 'add'},
                                             {   'type': 'join_from_list',
                                                 'value_path': ['doi'],
                                                 'dedupe': True,
                                                 'to': 'doi'},
                                             {'type': 'drop'}]},
    'publisher.uuid': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'publisher_uuid'}]},
    'publicationSeries': {   'actions': [   {'type': 'add'},
                                            {   'type': 'join_from_list',
                                                'value_path': ['name', 'value'],
                                                'to': 'publicationSeries'}]},
    'electronicISBNs': {   'actions': [   {'type': 'add'},
                                          {   'type': 'join_from_list',
                                              'value_path': [],
                                              'to': 'isbn_electronic'},
                                          {'type': 'drop'}]},
    'printISBNs': {   'actions': [   {'type': 'add'},
                                     {   'type': 'join_from_list',
                                         'value_path': [],
                                         'to': 'isbn_print'},
                                     {'type': 'drop'}]},
    'hostPublicationEditors': {   'actions': [   {'type': 'add'},
                                                 {   'type': 'join_from_list',
                                                     'value_paths': [['firstName'], ['lastName']],
                                                     'item_separator': ' ',
                                                     'to': 'hostPublicationEditors'}]},
    'hostPublicationTitle.value': {   'actions': [   {'type': 'add'},
                                                     {'type': 'rename', 'to': 'host_title'}]},
    'hostPublicationSubTitle.value': {   'actions': [   {'type': 'add'},
                                                        {'type': 'rename', 'to': 'host_subtitle'}]},
    'visibility.description.en_GB': {   'actions': [   {'type': 'add'},
                                                       {'type': 'rename', 'to': 'visibility'}]},
    'workflow.description.en_GB': {   'actions': [   {'type': 'add'},
                                                     {'type': 'rename', 'to': 'workflow'}]},
    'patentNumber': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'patent_number'}]},
    'country.term.en_GB': {'actions': [{'type': 'add'}, {'type': 'rename', 'to': 'country'}]}}
